In [1]:
import numpy as np
import pandas as pd

In [26]:
"""Pandas Operations"""

'Pandas Operations'

In [2]:
data = pd.read_csv('/content/train (1).csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198000 entries, 0 to 197999
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   created_date  198000 non-null  object
 1   post_id       198000 non-null  int64 
 2   emoticon_1    198000 non-null  int64 
 3   emoticon_2    198000 non-null  int64 
 4   emoticon_3    198000 non-null  int64 
 5   upvote        198000 non-null  int64 
 6   downvote      198000 non-null  int64 
 7   if_1          198000 non-null  int64 
 8   if_2          198000 non-null  int64 
 9   race          52577 non-null   object
 10  religion      52577 non-null   object
 11  gender        52577 non-null   object
 12  disability    198000 non-null  bool  
 13  comment       197999 non-null  object
 14  label         198000 non-null  int64 
dtypes: bool(1), int64(9), object(5)
memory usage: 21.3+ MB


In [6]:
print(data)

                            created_date  post_id  emoticon_1  emoticon_2  \
0       2024-01-18 08:43:57.397508+00:00       73           0           0   
1       2024-03-24 21:43:11.490017+00:00       39           0           0   
2       2024-04-24 20:32:17.014931+00:00       31           0           1   
3       2023-05-28 22:00:14.214527+00:00       39           0           0   
4       2023-09-09 23:12:05.689498+00:00       39           0           0   
...                                  ...      ...         ...         ...   
197995  2023-02-04 10:39:30.581185+00:00       39           0           0   
197996  2023-11-01 17:16:51.337370+00:00       72           0           0   
197997  2024-03-09 15:46:22.542539+00:00       72           0           0   
197998  2023-08-07 17:23:40.163756+00:00       72           0           1   
197999  2023-08-26 19:36:00.380158+00:00       72           0           0   

        emoticon_3  upvote  downvote  if_1  if_2   race religion gender  \


In [7]:
data.describe()

post_id     emoticon_1     emoticon_2     emoticon_3  \
count  198000.000000  198000.000000  198000.000000  198000.000000   
mean       68.447429       0.279768       0.048338       0.121071   
std        27.948390       1.023234       0.258477       0.481013   
min        20.000000       0.000000       0.000000       0.000000   
25%        39.000000       0.000000       0.000000       0.000000   
50%        72.000000       0.000000       0.000000       0.000000   
75%        72.000000       0.000000       0.000000       0.000000   
max       129.000000      47.000000      11.000000      17.000000   

              upvote       downvote           if_1           if_2  \
count  198000.000000  198000.000000  198000.000000  198000.000000   
mean        2.607975       0.666394       1.906152       7.956212   
std         5.054763       2.044335      25.635752      14.839464   
min         0.000000       0.000000       0.000000       3.000000   
25%         0.000000       0.000000       0.000000       4.000000   
50%         1.000000       0.000000       0.000000       6.000000   
75%         3.000000       1.000000       4.000000      10.000000   
max       201.000000     107.000000    1860.000000    1833.000000   

               label  
count  198000.000000  
mean        0.793965  
std         0.979808  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         2.000000  
max         3.000000

In [8]:
data.isnull().sum()

created_date         0
post_id              0
emoticon_1           0
emoticon_2           0
emoticon_3           0
upvote               0
downvote             0
if_1                 0
if_2                 0
race            145423
religion        145423
gender          145423
disability           0
comment              1
label                0
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(0)

In [13]:
data.mean(numeric_only=True)

post_id       68.447429
emoticon_1     0.279768
emoticon_2     0.048338
emoticon_3     0.121071
upvote         2.607975
downvote       0.666394
if_1           1.906152
if_2           7.956212
disability     0.013854
label          0.793965
dtype: float64

In [14]:
data.min(numeric_only=True)

post_id          20
emoticon_1        0
emoticon_2        0
emoticon_3        0
upvote            0
downvote          0
if_1              0
if_2              3
disability    False
label             0
dtype: object

In [16]:
data.max(numeric_only=True)

post_id        129
emoticon_1      47
emoticon_2      11
emoticon_3      17
upvote         201
downvote       107
if_1          1860
if_2          1833
disability    True
label            3
dtype: object

In [17]:
data.corr(numeric_only=True)

post_id  emoticon_1  emoticon_2  emoticon_3    upvote  downvote  \
post_id     1.000000    0.034567    0.012501    0.049622 -0.019455  0.065511   
emoticon_1  0.034567    1.000000    0.092087    0.144864  0.128124  0.177236   
emoticon_2  0.012501    0.092087    1.000000    0.140236  0.081580  0.169366   
emoticon_3  0.049622    0.144864    0.140236    1.000000  0.170662  0.371039   
upvote     -0.019455    0.128124    0.081580    0.170662  1.000000  0.314557   
downvote    0.065511    0.177236    0.169366    0.371039  0.314557  1.000000   
if_1       -0.000977   -0.002624    0.001741   -0.000514 -0.001654  0.000354   
if_2        0.010235   -0.004116    0.003919    0.007191 -0.000674  0.006307   
disability -0.010910   -0.005887    0.000235   -0.001087  0.002080 -0.003465   
label       0.022063   -0.003218    0.021597    0.027273  0.040181  0.044908   

                if_1      if_2  disability     label  
post_id    -0.000977  0.010235   -0.010910  0.022063  
emoticon_1 -0.002624 -0.004116   -0.005887 -0.003218  
emoticon_2  0.001741  0.003919    0.000235  0.021597  
emoticon_3 -0.000514  0.007191   -0.001087  0.027273  
upvote     -0.001654 -0.000674    0.002080  0.040181  
downvote    0.000354  0.006307   -0.003465  0.044908  
if_1        1.000000  0.008174    0.129887  0.007543  
if_2        0.008174  1.000000    0.023374  0.232902  
disability  0.129887  0.023374    1.000000  0.053809  
label       0.007543  0.232902    0.053809  1.000000

In [25]:
"""Numpy Operations"""

'Numpy Operations'

In [19]:
numeric_df = data.select_dtypes(include=np.number)
data_np = numeric_df.to_numpy()

In [20]:
print("Min values:\n", np.nanmin(data_np, axis=0))
print("Max values:\n", np.nanmax(data_np, axis=0))

Min values:
 [20  0  0  0  0  0  0  3  0]
Max values:
 [ 129   47   11   17  201  107 1860 1833    3]


In [21]:
print("\nPercentiles (25,50,75):\n",
      np.nanpercentile(data_np, [25, 50, 75], axis=0))


Percentiles (25,50,75):
 [[39.  0.  0.  0.  0.  0.  0.  4.  0.]
 [72.  0.  0.  0.  1.  0.  0.  6.  0.]
 [72.  0.  0.  0.  3.  1.  4. 10.  2.]]


In [22]:
mean_np = np.nanmean(data_np, axis=0)
std_np = np.nanstd(data_np, axis=0)

In [23]:
print("\nNumPy Mean:\n", mean_np)
print("\nNumPy Std:\n", std_np)


NumPy Mean:
 [6.84474293e+01 2.79767677e-01 4.83383838e-02 1.21070707e-01
 2.60797475e+00 6.66393939e-01 1.90615152e+00 7.95621212e+00
 7.93964646e-01]

NumPy Std:
 [27.94831926  1.02323154  0.25847604  0.48101163  5.05475054  2.04432941
 25.63568714 14.8394268   0.97980566]


In [24]:
zscore_data = (data_np - mean_np) / std_np
print("\nZ-score sample (first 5 rows):\n", zscore_data[:5])


Z-score sample (first 5 rows):
 [[ 0.16289247 -0.27341581 -0.18701301 -0.25170017 -0.51594529  0.16318606
  -0.07435539  0.13772687  1.23089241]
 [-1.05363865 -0.27341581 -0.18701301 -0.25170017  0.6710569  -0.3259719
  -0.07435539 -0.26660141 -0.8103287 ]
 [-1.33988126 -0.27341581  3.68181748  1.82725165 -0.51594529 -0.3259719
  -0.07435539  0.13772687  1.23089241]
 [-1.05363865 -0.27341581 -0.18701301 -0.25170017  0.4732232  -0.3259719
  -0.07435539  0.13772687  1.23089241]
 [-1.05363865 -0.27341581 -0.18701301 -0.25170017 -0.51594529 -0.3259719
  -0.07435539  0.13772687  1.23089241]]
